import type { Product, ProductCategory } from "@/lib/products";

export const REAL_MENU_CATEGORIES: ProductCategory[] = [
  { key: "burgers", label: "Hamburguesas", sort_order: 1, active: true, menu_shifts: ["dinner"] },
  {
    key: "sides",
    label: "Papas y acompaniamientos",
    sort_order: 2,
    active: true,
    menu_shifts: ["dinner"],
  },
  { key: "combos", label: "Combos", sort_order: 3, active: true, menu_shifts: ["dinner"] },
  { key: "proteico", label: "Menu proteico", sort_order: 4, active: true, menu_shifts: ["lunch"] },
  {
    key: "drinks",
    label: "Bebidas",
    sort_order: 5,
    active: true,
    menu_shifts: ["lunch", "dinner"],
  },
  { key: "extras", label: "Extras", sort_order: 6, active: true, menu_shifts: ["lunch", "dinner"] },
];

export const REAL_MENU_PRODUCTS: Product[] = [
  {
    id: "real-big-mc",
    name: "BIG MC",
    description:
      "Doble carne, doble cheddar, salsita BIG MC, lechuga y pepinillos. Todas nuestras hamburguesas son dobles y vienen con papas.",
    price: 16000,
    category: "burgers",
    image_url: "/src/assets/burger-double.jpg",
    badge: "NUEVA",
    available: true,
    sort_order: 1,
    ingredients: [
      "Doble carne",
      "Doble cheddar",
      "Salsita BIG MC",
      "Lechuga",
      "Pepinillos",
      "Papas",
    ],
  },
  {
    id: "real-terra-burguer",
    name: "Terra Burguer",
    description:
      "BBQ, cebolla crispy, desmechadito de roast beef, crema griega y verdeito fino. Edición limitada. Viene con papas.",
    price: 17000,
    category: "burgers",
    image_url: "/src/assets/burger-spicy.jpg",
    badge: "LIMITADA",
    available: true,
    sort_order: 2,
    ingredients: [
      "Doble carne",
      "BBQ",
      "Cebolla crispy",
      "Roast beef desmechado",
      "Crema griega",
      "Verdeito fino",
      "Papas",
    ],
  },
  {
    id: "real-cuarto-heinz",
    name: "Cuarto Heinz Burguer",
    description:
      "Doble carne, doble cheddar, aderezos Heinz importados, mayonesa, mostaza, ketchup, cebollita cruda y pepinillos de la casa. Viene con papas.",
    price: 16000,
    category: "burgers",
    image_url: "/src/assets/burger-classic.jpg",
    badge: "USA",
    available: true,
    sort_order: 3,
    ingredients: [
      "Doble carne",
      "Doble cheddar",
      "Mayonesa Heinz",
      "Mostaza Heinz",
      "Ketchup Heinz",
      "Cebolla cruda",
      "Pepinillos",
      "Papas",
    ],
  },
  {
    id: "real-sweet-baby",
    name: "Sweet Baby",
    description:
      "Doble carne, doble cheddar, Sweet Baby BBQ importada, cebolla caramel, bacon y aros de cebolla. Viene con papas.",
    price: 17000,
    category: "burgers",
    image_url: "/src/assets/burger-spicy.jpg",
    badge: "USA",
    available: true,
    sort_order: 4,
    ingredients: [
      "Doble carne",
      "Doble cheddar",
      "Sweet Baby BBQ",
      "Cebolla caramel",
      "Bacon",
      "Aros de cebolla",
      "Papas",
    ],
  },
  {
    id: "real-golden-hots",
    name: "Golden Hot's",
    description:
      "Alioli de verdeo, doble carne, doble cheddar, mermelada de bacon y full cebollita crispy. Viene con papas.",
    price: 17000,
    category: "burgers",
    image_url: "/src/assets/burger-double.jpg",
    badge: "TOP",
    available: true,
    sort_order: 5,
    ingredients: [
      "Doble carne",
      "Doble cheddar",
      "Alioli de verdeo",
      "Mermelada de bacon",
      "Cebollita crispy",
      "Papas",
    ],
  },
  {
    id: "real-la-rasta",
    name: "La Rasta",
    description:
      "Alioli de roque, cebolla caramel, doble carne, provolone y parra verde de rúcula. Viene con papas.",
    price: 16000,
    category: "burgers",
    image_url: "/src/assets/burger-veggie.jpg",
    badge: null,
    available: true,
    sort_order: 6,
    ingredients: [
      "Doble carne",
      "Provolone",
      "Alioli de roque",
      "Cebolla caramel",
      "Rúcula",
      "Papas",
    ],
  },
  {
    id: "real-la-gaucha",
    name: "La Gaucha",
    description:
      "Mayonesa, doble carne, queso ahumado, criolla ahumada y parra verde de rúcula. Viene con papas.",
    price: 15000,
    category: "burgers",
    image_url: "/src/assets/burger-classic.jpg",
    badge: null,
    available: true,
    sort_order: 7,
    ingredients: ["Doble carne", "Queso ahumado", "Mayonesa", "Criolla ahumada", "Rúcula", "Papas"],
  },
  {
    id: "real-hots-checken",
    name: "Hot's Checken",
    description: "Mayo picante, dedos de pollo x3, lechuga, tomate y mostaza. Viene con papas.",
    price: 15500,
    category: "burgers",
    image_url: "/src/assets/burger-spicy.jpg",
    badge: "POLLO",
    available: true,
    sort_order: 8,
    ingredients: ["Dedos de pollo x3", "Mayo picante", "Lechuga", "Tomate", "Mostaza", "Papas"],
  },
  {
    id: "real-baco-burguer",
    name: "BACO BURGUER",
    description:
      "Doble carne, cheddar, cebollita al vino tinto, aros de cebolla, bacon, BBQ y alioli. Viene con papas.",
    price: 16000,
    category: "burgers",
    image_url: "/src/assets/burger-double.jpg",
    badge: null,
    available: true,
    sort_order: 9,
    ingredients: [
      "Doble carne",
      "Cheddar",
      "Cebollita al vino tinto",
      "Aros de cebolla",
      "Bacon",
      "BBQ",
      "Alioli",
      "Papas",
    ],
  },
  {
    id: "real-american",
    name: "AMERICAN",
    description:
      "Doble carne, cheddar, cebollita, lechuga, tomate, pepinillos y una bomba de salsas: thousand, alioli y ketchup. Viene con papas.",
    price: 16000,
    category: "burgers",
    image_url: "/src/assets/burger-classic.jpg",
    badge: null,
    available: true,
    sort_order: 10,
    ingredients: [
      "Doble carne",
      "Cheddar",
      "Cebollita",
      "Lechuga",
      "Tomate",
      "Pepinillos",
      "Thousand",
      "Alioli",
      "Ketchup",
      "Papas",
    ],
  },
  {
    id: "real-crispy",
    name: "CRISPY",
    description:
      "Doble carne, doble cheddar, bacon, cebolla crispy y el toque de barbacoa y alioli. Viene con papas.",
    price: 16000,
    category: "burgers",
    image_url: "/src/assets/burger-spicy.jpg",
    badge: null,
    available: true,
    sort_order: 11,
    ingredients: [
      "Doble carne",
      "Doble cheddar",
      "Bacon",
      "Cebolla crispy",
      "Barbacoa",
      "Alioli",
      "Papas",
    ],
  },
  {
    id: "real-cheese-burger",
    name: "CHEESE BURGER",
    description: "Simple pero letal: doble carne, doble cheddar y nada más. Viene con papas.",
    price: 13500,
    category: "burgers",
    image_url: "/src/assets/burger-double.jpg",
    badge: null,
    available: true,
    sort_order: 12,
    ingredients: ["Doble carne", "Doble cheddar", "Papas"],
  },
  {
    id: "real-hotspot-classic",
    name: "HOTSPOT CLASSIC",
    description:
      "Doble carne, doble cheddar, cebollita cruda y el mix perfecto: ketchup y thousand. Viene con papas.",
    price: 14000,
    category: "burgers",
    image_url: "/src/assets/burger-classic.jpg",
    badge: "TOP",
    available: true,
    sort_order: 13,
    ingredients: [
      "Doble carne",
      "Doble cheddar",
      "Cebollita cruda",
      "Ketchup",
      "Thousand",
      "Papas",
    ],
  },
  {
    id: "real-bbq",
    name: "BBQ",
    description:
      "Doble carne, doble cheddar, cebollita caramel, bacon y barbacoa. Viene con papas.",
    price: 16000,
    category: "burgers",
    image_url: "/src/assets/burger-spicy.jpg",
    badge: null,
    available: true,
    sort_order: 14,
    ingredients: [
      "Doble carne",
      "Doble cheddar",
      "Cebollita caramel",
      "Bacon",
      "Barbacoa",
      "Papas",
    ],
  },
  {
    id: "real-provolone",
    name: "PROVOLONE",
    description: "Doble carne, doble provolone, bacon, ketchup y alioli. Viene con papas.",
    price: 16000,
    category: "burgers",
    image_url: "/src/assets/burger-double.jpg",
    badge: null,
    available: true,
    sort_order: 15,
    ingredients: ["Doble carne", "Doble provolone", "Bacon", "Ketchup", "Alioli", "Papas"],
  },
  {
    id: "real-zapiola",
    name: "ZAPIOLA BURGUER",
    description:
      "Doble carne smasheada con cebolla, doble cheddar, mostaza y pepinillos. Viene con papas.",
    price: 14500,
    category: "burgers",
    image_url: "/src/assets/burger-classic.jpg",
    badge: null,
    available: true,
    sort_order: 16,
    ingredients: [
      "Doble carne smasheada",
      "Cebolla",
      "Doble cheddar",
      "Mostaza",
      "Pepinillos",
      "Papas",
    ],
  },
  {
    id: "real-papas-crosstrax",
    name: "Papas Crosstrax solas",
    description: "Papas tipo Crosstrax o regillas. Porción para compartir.",
    price: 12000,
    category: "sides",
    image_url: "/src/assets/side-fries.jpg",
    badge: null,
    available: true,
    sort_order: 101,
    ingredients: ["Papas Crosstrax"],
  },
  {
    id: "real-papas-crosstrax-cheddar",
    name: "Papas Crosstrax con cheddar",
    description: "Papas tipo Crosstrax o regillas con cheddar. Porción para compartir.",
    price: 16000,
    category: "sides",
    image_url: "/src/assets/side-fries.jpg",
    badge: null,
    available: true,
    sort_order: 102,
    ingredients: ["Papas Crosstrax", "Cheddar"],
  },
  {
    id: "real-desmechadito-crosstrax",
    name: "Desmechadito Crosstrax",
    description: "Papas tipo Crosstrax o regillas con desmechadito. Porción para compartir.",
    price: 20000,
    category: "sides",
    image_url: "/src/assets/side-fries.jpg",
    badge: "FULL",
    available: true,
    sort_order: 103,
    ingredients: ["Papas Crosstrax", "Desmechadito"],
  },
  {
    id: "real-papas-cheddar",
    name: "Papas con cheddar",
    description: "Papas con cheddar, alioli, bacon y verdeo. Ideal para compartir.",
    price: 14000,
    category: "sides",
    image_url: "/src/assets/side-fries.jpg",
    badge: null,
    available: true,
    sort_order: 104,
    ingredients: ["Papas", "Cheddar", "Alioli", "Bacon", "Verdeo"],
  },
  {
    id: "real-papas-individuales",
    name: "Papas individuales",
    description: "Porción individual de papas.",
    price: 7000,
    category: "sides",
    image_url: "/src/assets/side-fries.jpg",
    badge: null,
    available: true,
    sort_order: 105,
    ingredients: ["Papas"],
  },
  {
    id: "real-nuggets-aros-18",
    name: "Nuggets o aros de cebolla x18",
    description: "Elegí nuggets o aros de cebolla. Porción de 18 unidades.",
    price: 14000,
    category: "sides",
    image_url: "/src/assets/side-rings.jpg",
    badge: null,
    available: true,
    sort_order: 106,
    ingredients: ["Nuggets o aros de cebolla"],
  },
  {
    id: "real-nuggets-aros-7",
    name: "Nuggets o aros de cebolla x7",
    description: "Elegí nuggets o aros de cebolla. Porción de 7 unidades.",
    price: 7000,
    category: "sides",
    image_url: "/src/assets/side-rings.jpg",
    badge: null,
    available: true,
    sort_order: 107,
    ingredients: ["Nuggets o aros de cebolla"],
  },
  {
    id: "real-dedos-pollo-10",
    name: "Dedos de pollo x10",
    description: "Dedos de pollo, porción de 10 unidades.",
    price: 14000,
    category: "sides",
    image_url: "/src/assets/side-rings.jpg",
    badge: "POLLO",
    available: true,
    sort_order: 108,
    ingredients: ["Dedos de pollo"],
  },
  {
    id: "real-dedos-pollo-5",
    name: "Dedos de pollo x5",
    description: "Dedos de pollo, porción de 5 unidades.",
    price: 5000,
    category: "sides",
    image_url: "/src/assets/side-rings.jpg",
    badge: "POLLO",
    available: true,
    sort_order: 109,
    ingredients: ["Dedos de pollo"],
  },
  {
    id: "real-mystery-box",
    name: "Mystery Box",
    description: "2 Cheesebacon en una pileta de cheddar + papas x2 + nuggets x1 + 2 bebidas.",
    price: 40000,
    category: "combos",
    image_url: "/src/assets/burger-double.jpg",
    badge: "BOX",
    available: true,
    sort_order: 201,
    ingredients: ["2 Cheesebacon", "Cheddar", "Papas x2", "Nuggets x1", "2 bebidas"],
  },
  {
    id: "real-mystery-box-individual",
    name: "Mystery Box individual",
    description: "Versión individual de la Mystery Box.",
    price: 20000,
    category: "combos",
    image_url: "/src/assets/burger-double.jpg",
    badge: "BOX",
    available: true,
    sort_order: 202,
    ingredients: ["Cheesebacon", "Cheddar", "Papas", "Nuggets", "Bebida"],
  },
  {
    id: "real-pollito-crispy",
    name: "Pollito Crispy",
    description:
      "Mix de verdes, cherrys confitados, parmesano rallado, cubitos de queso, huevo poché, alioli cítrico. Opcional: vinagreta de mostaza y miel.",
    price: 16000,
    category: "proteico",
    image_url: "/src/assets/burger-veggie.jpg",
    badge: "PROTE",
    available: true,
    sort_order: 301,
    ingredients: [
      "Mix de verdes",
      "Cherrys confitados",
      "Parmesano",
      "Cubitos de queso",
      "Huevo poché",
      "Alioli cítrico",
    ],
  },
  {
    id: "real-full-prote",
    name: "Full Prote",
    description:
      "Mix de verdes, endivias, palta, cherrys confitados, parmesano, cubitos de queso, albahaca fresca, ricota, huevo poché, churrasquito de cuadril, frutos secos tostados y alioli de la casa.",
    price: 18000,
    category: "proteico",
    image_url: "/src/assets/burger-veggie.jpg",
    badge: "PROTE",
    available: true,
    sort_order: 302,
    ingredients: [
      "Mix de verdes",
      "Endivias",
      "Palta",
      "Cherrys",
      "Parmesano",
      "Ricota",
      "Huevo poché",
      "Cuadril",
      "Frutos secos",
      "Alioli",
    ],
  },
  {
    id: "real-turbo-carbo",
    name: "Turbo Carbo",
    description:
      "Pasta, cebollita morada, zanahoria, morrón en brunoise, choclo, mayo de palta, verdeo, atún, huevo poché y frutos secos tostados.",
    price: 16000,
    category: "proteico",
    image_url: "/src/assets/burger-veggie.jpg",
    badge: "PROTE",
    available: true,
    sort_order: 303,
    ingredients: [
      "Pasta",
      "Cebolla morada",
      "Zanahoria",
      "Morrón",
      "Choclo",
      "Mayo de palta",
      "Verdeo",
      "Atún",
      "Huevo poché",
      "Frutos secos",
    ],
  },
  {
    id: "real-cesar-casa",
    name: "César de la casa",
    description:
      "Mix de verdes, parmesano rallado, cubitos de queso, pollito salteado, crutones, huevo poché, césar de la casa y lluvia de semillas.",
    price: 16000,
    category: "proteico",
    image_url: "/src/assets/burger-veggie.jpg",
    badge: "PROTE",
    available: true,
    sort_order: 304,
    ingredients: [
      "Mix de verdes",
      "Parmesano",
      "Cubitos de queso",
      "Pollo salteado",
      "Crutones",
      "Huevo poché",
      "César de la casa",
      "Semillas",
    ],
  },
  {
    id: "real-oriental-style",
    name: "Oriental Style",
    description:
      "Fideos de arroz con vegetales salteados: zuchinis, zanahoria, champiñón, morrón amarillo, cebolla, brotes de soja, huevito coreano, verdeo y mix de semillas.",
    price: 16000,
    category: "proteico",
    image_url: "/src/assets/burger-veggie.jpg",
    badge: "PROTE",
    available: true,
    sort_order: 305,
    ingredients: [
      "Fideos de arroz",
      "Zuchinis",
      "Zanahoria",
      "Champiñón",
      "Morrón amarillo",
      "Cebolla",
      "Brotes de soja",
      "Huevo coreano",
      "Verdeo",
      "Semillas",
    ],
  },
  {
    id: "real-agregado-pollo",
    name: "Agregado de pollo",
    description: "Opcional para menú proteico.",
    price: 4000,
    category: "extras",
    image_url: "/src/assets/side-rings.jpg",
    badge: null,
    available: true,
    sort_order: 401,
    ingredients: ["Pollo"],
  },
  {
    id: "real-agregado-gambas",
    name: "Agregado de gambas y salsa de ostras",
    description: "Opcional para Oriental Style.",
    price: 7000,
    category: "extras",
    image_url: "/src/assets/side-rings.jpg",
    badge: null,
    available: true,
    sort_order: 402,
    ingredients: ["Gambas", "Salsa de ostras"],
  },
  {
    id: "real-agranda-burguer",
    name: "Agrandá tu burguer",
    description: "Agregá más carne y más cheddar a tu hamburguesa.",
    price: 3500,
    category: "extras",
    image_url: "/src/assets/burger-double.jpg",
    badge: "EXTRA",
    available: true,
    sort_order: 403,
    ingredients: ["Carne extra", "Cheddar extra"],
  },
  {
    id: "real-lata-pepsi-7up",
    name: "Lata Pepsi o 7up",
    description: "Lata de gaseosa Pepsi o 7up.",
    price: 2500,
    category: "drinks",
    image_url: "/src/assets/drink-cola.jpg",
    badge: null,
    available: true,
    sort_order: 501,
    ingredients: [],
  },
  {
    id: "real-lata-cerveza",
    name: "Lata de cerveza",
    description: "Cerveza en lata.",
    price: 5000,
    category: "drinks",
    image_url: "/src/assets/drink-shake.jpg",
    badge: null,
    available: true,
    sort_order: 502,
    ingredients: [],
  },
];
