/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MiCuentaRouteImport } from './routes/mi-cuenta'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockSlugRouteImport } from './routes/stock.$slug'
import { Route as AdminVentaLocalRouteImport } from './routes/admin.venta-local'
import { Route as AdminStockRouteImport } from './routes/admin.stock'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminHistorialRouteImport } from './routes/admin.historial'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as ApiStoreOrdersRouteImport } from './routes/api.store.orders'
import { Route as ApiStoreMenuRouteImport } from './routes/api.store.menu'
import { Route as ApiAdminLocalSaleRouteImport } from './routes/api.admin.local-sale'
import { Route as ApiAdminInventoryRouteImport } from './routes/api.admin.inventory'
import { Route as ApiAdminDayRouteImport } from './routes/api.admin.day'
import { Route as ApiAdminConfigRouteImport } from './routes/api.admin.config'
import { Route as ApiAdminCategoriesRouteImport } from './routes/api.admin.categories'
import { Route as ApiStoreAuthResetPasswordRouteImport } from './routes/api.store.auth.reset-password'
import { Route as ApiStoreAuthRegisterRouteImport } from './routes/api.store.auth.register'
import { Route as ApiStoreAuthProfileRouteImport } from './routes/api.store.auth.profile'
import { Route as ApiStoreAuthOrdersRouteImport } from './routes/api.store.auth.orders'
import { Route as ApiStoreAuthMeRouteImport } from './routes/api.store.auth.me'
import { Route as ApiStoreAuthLogoutRouteImport } from './routes/api.store.auth.logout'
import { Route as ApiStoreAuthLoginRouteImport } from './routes/api.store.auth.login'
import { Route as ApiStoreAuthGoogleRouteImport } from './routes/api.store.auth.google'
import { Route as ApiStoreAuthForgotPasswordRouteImport } from './routes/api.store.auth.forgot-password'
import { Route as ApiAdminPushSubscriptionsRouteImport } from './routes/api.admin.push.subscriptions'
import { Route as ApiAdminPushConfigRouteImport } from './routes/api.admin.push.config'
import { Route as ApiAdminOrdersStatusRouteImport } from './routes/api.admin.orders.status'
import { Route as ApiAdminOrdersEditRouteImport } from './routes/api.admin.orders.edit'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MiCuentaRoute = MiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockSlugRoute = StockSlugRouteImport.update({
  id: '/stock/$slug',
  path: '/stock/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVentaLocalRoute = AdminVentaLocalRouteImport.update({
  id: '/venta-local',
  path: '/venta-local',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistorialRoute = AdminHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const ApiStoreOrdersRoute = ApiStoreOrdersRouteImport.update({
  id: '/api/store/orders',
  path: '/api/store/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreMenuRoute = ApiStoreMenuRouteImport.update({
  id: '/api/store/menu',
  path: '/api/store/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLocalSaleRoute = ApiAdminLocalSaleRouteImport.update({
  id: '/api/admin/local-sale',
  path: '/api/admin/local-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInventoryRoute = ApiAdminInventoryRouteImport.update({
  id: '/api/admin/inventory',
  path: '/api/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDayRoute = ApiAdminDayRouteImport.update({
  id: '/api/admin/day',
  path: '/api/admin/day',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminConfigRoute = ApiAdminConfigRouteImport.update({
  id: '/api/admin/config',
  path: '/api/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCategoriesRoute = ApiAdminCategoriesRouteImport.update({
  id: '/api/admin/categories',
  path: '/api/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreAuthResetPasswordRoute =
  ApiStoreAuthResetPasswordRouteImport.update({
    id: '/api/store/auth/reset-password',
    path: '/api/store/auth/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStoreAuthRegisterRoute = ApiStoreAuthRegisterRouteImport.update({
  id: '/api/store/auth/register',
  path: '/api/store/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreAuthProfileRoute = ApiStoreAuthProfileRouteImport.update({
  id: '/api/store/auth/profile',
  path: '/api/store/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreAuthOrdersRoute = ApiStoreAuthOrdersRouteImport.update({
  id: '/api/store/auth/orders',
  path: '/api/store/auth/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreAuthMeRoute = ApiStoreAuthMeRouteImport.update({
  id: '/api/store/auth/me',
  path: '/api/store/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreAuthLogoutRoute = ApiStoreAuthLogoutRouteImport.update({
  id: '/api/store/auth/logout',
  path: '/api/store/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreAuthLoginRoute = ApiStoreAuthLoginRouteImport.update({
  id: '/api/store/auth/login',
  path: '/api/store/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreAuthGoogleRoute = ApiStoreAuthGoogleRouteImport.update({
  id: '/api/store/auth/google',
  path: '/api/store/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreAuthForgotPasswordRoute =
  ApiStoreAuthForgotPasswordRouteImport.update({
    id: '/api/store/auth/forgot-password',
    path: '/api/store/auth/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminPushSubscriptionsRoute =
  ApiAdminPushSubscriptionsRouteImport.update({
    id: '/api/admin/push/subscriptions',
    path: '/api/admin/push/subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminPushConfigRoute = ApiAdminPushConfigRouteImport.update({
  id: '/api/admin/push/config',
  path: '/api/admin/push/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersStatusRoute = ApiAdminOrdersStatusRouteImport.update({
  id: '/api/admin/orders/status',
  path: '/api/admin/orders/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersEditRoute = ApiAdminOrdersEditRouteImport.update({
  id: '/api/admin/orders/edit',
  path: '/api/admin/orders/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/historial': typeof AdminHistorialRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/venta-local': typeof AdminVentaLocalRoute
  '/stock/$slug': typeof StockSlugRoute
  '/api/admin/categories': typeof ApiAdminCategoriesRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/day': typeof ApiAdminDayRoute
  '/api/admin/inventory': typeof ApiAdminInventoryRoute
  '/api/admin/local-sale': typeof ApiAdminLocalSaleRoute
  '/api/store/menu': typeof ApiStoreMenuRoute
  '/api/store/orders': typeof ApiStoreOrdersRoute
  '/api/admin/orders/edit': typeof ApiAdminOrdersEditRoute
  '/api/admin/orders/status': typeof ApiAdminOrdersStatusRoute
  '/api/admin/push/config': typeof ApiAdminPushConfigRoute
  '/api/admin/push/subscriptions': typeof ApiAdminPushSubscriptionsRoute
  '/api/store/auth/forgot-password': typeof ApiStoreAuthForgotPasswordRoute
  '/api/store/auth/google': typeof ApiStoreAuthGoogleRoute
  '/api/store/auth/login': typeof ApiStoreAuthLoginRoute
  '/api/store/auth/logout': typeof ApiStoreAuthLogoutRoute
  '/api/store/auth/me': typeof ApiStoreAuthMeRoute
  '/api/store/auth/orders': typeof ApiStoreAuthOrdersRoute
  '/api/store/auth/profile': typeof ApiStoreAuthProfileRoute
  '/api/store/auth/register': typeof ApiStoreAuthRegisterRoute
  '/api/store/auth/reset-password': typeof ApiStoreAuthResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/historial': typeof AdminHistorialRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/venta-local': typeof AdminVentaLocalRoute
  '/stock/$slug': typeof StockSlugRoute
  '/api/admin/categories': typeof ApiAdminCategoriesRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/day': typeof ApiAdminDayRoute
  '/api/admin/inventory': typeof ApiAdminInventoryRoute
  '/api/admin/local-sale': typeof ApiAdminLocalSaleRoute
  '/api/store/menu': typeof ApiStoreMenuRoute
  '/api/store/orders': typeof ApiStoreOrdersRoute
  '/api/admin/orders/edit': typeof ApiAdminOrdersEditRoute
  '/api/admin/orders/status': typeof ApiAdminOrdersStatusRoute
  '/api/admin/push/config': typeof ApiAdminPushConfigRoute
  '/api/admin/push/subscriptions': typeof ApiAdminPushSubscriptionsRoute
  '/api/store/auth/forgot-password': typeof ApiStoreAuthForgotPasswordRoute
  '/api/store/auth/google': typeof ApiStoreAuthGoogleRoute
  '/api/store/auth/login': typeof ApiStoreAuthLoginRoute
  '/api/store/auth/logout': typeof ApiStoreAuthLogoutRoute
  '/api/store/auth/me': typeof ApiStoreAuthMeRoute
  '/api/store/auth/orders': typeof ApiStoreAuthOrdersRoute
  '/api/store/auth/profile': typeof ApiStoreAuthProfileRoute
  '/api/store/auth/register': typeof ApiStoreAuthRegisterRoute
  '/api/store/auth/reset-password': typeof ApiStoreAuthResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/historial': typeof AdminHistorialRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/venta-local': typeof AdminVentaLocalRoute
  '/stock/$slug': typeof StockSlugRoute
  '/api/admin/categories': typeof ApiAdminCategoriesRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/day': typeof ApiAdminDayRoute
  '/api/admin/inventory': typeof ApiAdminInventoryRoute
  '/api/admin/local-sale': typeof ApiAdminLocalSaleRoute
  '/api/store/menu': typeof ApiStoreMenuRoute
  '/api/store/orders': typeof ApiStoreOrdersRoute
  '/api/admin/orders/edit': typeof ApiAdminOrdersEditRoute
  '/api/admin/orders/status': typeof ApiAdminOrdersStatusRoute
  '/api/admin/push/config': typeof ApiAdminPushConfigRoute
  '/api/admin/push/subscriptions': typeof ApiAdminPushSubscriptionsRoute
  '/api/store/auth/forgot-password': typeof ApiStoreAuthForgotPasswordRoute
  '/api/store/auth/google': typeof ApiStoreAuthGoogleRoute
  '/api/store/auth/login': typeof ApiStoreAuthLoginRoute
  '/api/store/auth/logout': typeof ApiStoreAuthLogoutRoute
  '/api/store/auth/me': typeof ApiStoreAuthMeRoute
  '/api/store/auth/orders': typeof ApiStoreAuthOrdersRoute
  '/api/store/auth/profile': typeof ApiStoreAuthProfileRoute
  '/api/store/auth/register': typeof ApiStoreAuthRegisterRoute
  '/api/store/auth/reset-password': typeof ApiStoreAuthResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/contacto'
    | '/forgot-password'
    | '/login'
    | '/menu'
    | '/mi-cuenta'
    | '/register'
    | '/reset-password'
    | '/sobre'
    | '/admin/configuracion'
    | '/admin/dashboard'
    | '/admin/historial'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/stock'
    | '/admin/venta-local'
    | '/stock/$slug'
    | '/api/admin/categories'
    | '/api/admin/config'
    | '/api/admin/day'
    | '/api/admin/inventory'
    | '/api/admin/local-sale'
    | '/api/store/menu'
    | '/api/store/orders'
    | '/api/admin/orders/edit'
    | '/api/admin/orders/status'
    | '/api/admin/push/config'
    | '/api/admin/push/subscriptions'
    | '/api/store/auth/forgot-password'
    | '/api/store/auth/google'
    | '/api/store/auth/login'
    | '/api/store/auth/logout'
    | '/api/store/auth/me'
    | '/api/store/auth/orders'
    | '/api/store/auth/profile'
    | '/api/store/auth/register'
    | '/api/store/auth/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/contacto'
    | '/forgot-password'
    | '/login'
    | '/menu'
    | '/mi-cuenta'
    | '/register'
    | '/reset-password'
    | '/sobre'
    | '/admin/configuracion'
    | '/admin/dashboard'
    | '/admin/historial'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/stock'
    | '/admin/venta-local'
    | '/stock/$slug'
    | '/api/admin/categories'
    | '/api/admin/config'
    | '/api/admin/day'
    | '/api/admin/inventory'
    | '/api/admin/local-sale'
    | '/api/store/menu'
    | '/api/store/orders'
    | '/api/admin/orders/edit'
    | '/api/admin/orders/status'
    | '/api/admin/push/config'
    | '/api/admin/push/subscriptions'
    | '/api/store/auth/forgot-password'
    | '/api/store/auth/google'
    | '/api/store/auth/login'
    | '/api/store/auth/logout'
    | '/api/store/auth/me'
    | '/api/store/auth/orders'
    | '/api/store/auth/profile'
    | '/api/store/auth/register'
    | '/api/store/auth/reset-password'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/contacto'
    | '/forgot-password'
    | '/login'
    | '/menu'
    | '/mi-cuenta'
    | '/register'
    | '/reset-password'
    | '/sobre'
    | '/admin/configuracion'
    | '/admin/dashboard'
    | '/admin/historial'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/stock'
    | '/admin/venta-local'
    | '/stock/$slug'
    | '/api/admin/categories'
    | '/api/admin/config'
    | '/api/admin/day'
    | '/api/admin/inventory'
    | '/api/admin/local-sale'
    | '/api/store/menu'
    | '/api/store/orders'
    | '/api/admin/orders/edit'
    | '/api/admin/orders/status'
    | '/api/admin/push/config'
    | '/api/admin/push/subscriptions'
    | '/api/store/auth/forgot-password'
    | '/api/store/auth/google'
    | '/api/store/auth/login'
    | '/api/store/auth/logout'
    | '/api/store/auth/me'
    | '/api/store/auth/orders'
    | '/api/store/auth/profile'
    | '/api/store/auth/register'
    | '/api/store/auth/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ContactoRoute: typeof ContactoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  MiCuentaRoute: typeof MiCuentaRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreRoute: typeof SobreRoute
  StockSlugRoute: typeof StockSlugRoute
  ApiAdminCategoriesRoute: typeof ApiAdminCategoriesRoute
  ApiAdminConfigRoute: typeof ApiAdminConfigRoute
  ApiAdminDayRoute: typeof ApiAdminDayRoute
  ApiAdminInventoryRoute: typeof ApiAdminInventoryRoute
  ApiAdminLocalSaleRoute: typeof ApiAdminLocalSaleRoute
  ApiStoreMenuRoute: typeof ApiStoreMenuRoute
  ApiStoreOrdersRoute: typeof ApiStoreOrdersRoute
  ApiAdminOrdersEditRoute: typeof ApiAdminOrdersEditRoute
  ApiAdminOrdersStatusRoute: typeof ApiAdminOrdersStatusRoute
  ApiAdminPushConfigRoute: typeof ApiAdminPushConfigRoute
  ApiAdminPushSubscriptionsRoute: typeof ApiAdminPushSubscriptionsRoute
  ApiStoreAuthForgotPasswordRoute: typeof ApiStoreAuthForgotPasswordRoute
  ApiStoreAuthGoogleRoute: typeof ApiStoreAuthGoogleRoute
  ApiStoreAuthLoginRoute: typeof ApiStoreAuthLoginRoute
  ApiStoreAuthLogoutRoute: typeof ApiStoreAuthLogoutRoute
  ApiStoreAuthMeRoute: typeof ApiStoreAuthMeRoute
  ApiStoreAuthOrdersRoute: typeof ApiStoreAuthOrdersRoute
  ApiStoreAuthProfileRoute: typeof ApiStoreAuthProfileRoute
  ApiStoreAuthRegisterRoute: typeof ApiStoreAuthRegisterRoute
  ApiStoreAuthResetPasswordRoute: typeof ApiStoreAuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-cuenta': {
      id: '/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof MiCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$slug': {
      id: '/stock/$slug'
      path: '/stock/$slug'
      fullPath: '/stock/$slug'
      preLoaderRoute: typeof StockSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/venta-local': {
      id: '/admin/venta-local'
      path: '/venta-local'
      fullPath: '/admin/venta-local'
      preLoaderRoute: typeof AdminVentaLocalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/historial': {
      id: '/admin/historial'
      path: '/historial'
      fullPath: '/admin/historial'
      preLoaderRoute: typeof AdminHistorialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/store/orders': {
      id: '/api/store/orders'
      path: '/api/store/orders'
      fullPath: '/api/store/orders'
      preLoaderRoute: typeof ApiStoreOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/menu': {
      id: '/api/store/menu'
      path: '/api/store/menu'
      fullPath: '/api/store/menu'
      preLoaderRoute: typeof ApiStoreMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/local-sale': {
      id: '/api/admin/local-sale'
      path: '/api/admin/local-sale'
      fullPath: '/api/admin/local-sale'
      preLoaderRoute: typeof ApiAdminLocalSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/inventory': {
      id: '/api/admin/inventory'
      path: '/api/admin/inventory'
      fullPath: '/api/admin/inventory'
      preLoaderRoute: typeof ApiAdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/day': {
      id: '/api/admin/day'
      path: '/api/admin/day'
      fullPath: '/api/admin/day'
      preLoaderRoute: typeof ApiAdminDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/config': {
      id: '/api/admin/config'
      path: '/api/admin/config'
      fullPath: '/api/admin/config'
      preLoaderRoute: typeof ApiAdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/categories': {
      id: '/api/admin/categories'
      path: '/api/admin/categories'
      fullPath: '/api/admin/categories'
      preLoaderRoute: typeof ApiAdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/auth/reset-password': {
      id: '/api/store/auth/reset-password'
      path: '/api/store/auth/reset-password'
      fullPath: '/api/store/auth/reset-password'
      preLoaderRoute: typeof ApiStoreAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/auth/register': {
      id: '/api/store/auth/register'
      path: '/api/store/auth/register'
      fullPath: '/api/store/auth/register'
      preLoaderRoute: typeof ApiStoreAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/auth/profile': {
      id: '/api/store/auth/profile'
      path: '/api/store/auth/profile'
      fullPath: '/api/store/auth/profile'
      preLoaderRoute: typeof ApiStoreAuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/auth/orders': {
      id: '/api/store/auth/orders'
      path: '/api/store/auth/orders'
      fullPath: '/api/store/auth/orders'
      preLoaderRoute: typeof ApiStoreAuthOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/auth/me': {
      id: '/api/store/auth/me'
      path: '/api/store/auth/me'
      fullPath: '/api/store/auth/me'
      preLoaderRoute: typeof ApiStoreAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/auth/logout': {
      id: '/api/store/auth/logout'
      path: '/api/store/auth/logout'
      fullPath: '/api/store/auth/logout'
      preLoaderRoute: typeof ApiStoreAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/auth/login': {
      id: '/api/store/auth/login'
      path: '/api/store/auth/login'
      fullPath: '/api/store/auth/login'
      preLoaderRoute: typeof ApiStoreAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/auth/google': {
      id: '/api/store/auth/google'
      path: '/api/store/auth/google'
      fullPath: '/api/store/auth/google'
      preLoaderRoute: typeof ApiStoreAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/auth/forgot-password': {
      id: '/api/store/auth/forgot-password'
      path: '/api/store/auth/forgot-password'
      fullPath: '/api/store/auth/forgot-password'
      preLoaderRoute: typeof ApiStoreAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/push/subscriptions': {
      id: '/api/admin/push/subscriptions'
      path: '/api/admin/push/subscriptions'
      fullPath: '/api/admin/push/subscriptions'
      preLoaderRoute: typeof ApiAdminPushSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/push/config': {
      id: '/api/admin/push/config'
      path: '/api/admin/push/config'
      fullPath: '/api/admin/push/config'
      preLoaderRoute: typeof ApiAdminPushConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/status': {
      id: '/api/admin/orders/status'
      path: '/api/admin/orders/status'
      fullPath: '/api/admin/orders/status'
      preLoaderRoute: typeof ApiAdminOrdersStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/edit': {
      id: '/api/admin/orders/edit'
      path: '/api/admin/orders/edit'
      fullPath: '/api/admin/orders/edit'
      preLoaderRoute: typeof ApiAdminOrdersEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminHistorialRoute: typeof AdminHistorialRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminStockRoute: typeof AdminStockRoute
  AdminVentaLocalRoute: typeof AdminVentaLocalRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminHistorialRoute: AdminHistorialRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminStockRoute: AdminStockRoute,
  AdminVentaLocalRoute: AdminVentaLocalRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ContactoRoute: ContactoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  MiCuentaRoute: MiCuentaRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreRoute: SobreRoute,
  StockSlugRoute: StockSlugRoute,
  ApiAdminCategoriesRoute: ApiAdminCategoriesRoute,
  ApiAdminConfigRoute: ApiAdminConfigRoute,
  ApiAdminDayRoute: ApiAdminDayRoute,
  ApiAdminInventoryRoute: ApiAdminInventoryRoute,
  ApiAdminLocalSaleRoute: ApiAdminLocalSaleRoute,
  ApiStoreMenuRoute: ApiStoreMenuRoute,
  ApiStoreOrdersRoute: ApiStoreOrdersRoute,
  ApiAdminOrdersEditRoute: ApiAdminOrdersEditRoute,
  ApiAdminOrdersStatusRoute: ApiAdminOrdersStatusRoute,
  ApiAdminPushConfigRoute: ApiAdminPushConfigRoute,
  ApiAdminPushSubscriptionsRoute: ApiAdminPushSubscriptionsRoute,
  ApiStoreAuthForgotPasswordRoute: ApiStoreAuthForgotPasswordRoute,
  ApiStoreAuthGoogleRoute: ApiStoreAuthGoogleRoute,
  ApiStoreAuthLoginRoute: ApiStoreAuthLoginRoute,
  ApiStoreAuthLogoutRoute: ApiStoreAuthLogoutRoute,
  ApiStoreAuthMeRoute: ApiStoreAuthMeRoute,
  ApiStoreAuthOrdersRoute: ApiStoreAuthOrdersRoute,
  ApiStoreAuthProfileRoute: ApiStoreAuthProfileRoute,
  ApiStoreAuthRegisterRoute: ApiStoreAuthRegisterRoute,
  ApiStoreAuthResetPasswordRoute: ApiStoreAuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
